### PR TITLE
Upgrade `pallet-faucets` to FRAME v2

### PR DESCRIPTION
**Pull request by Doordashcon**
TODO

- [x] Lib
- [x] Mock
- [x] Test
- [ ] Documentation
- [ ] Benchmarks

### CODE REVIEW

**Comment by Doordashcon** [comment]
tbh i think this pallet needs a change, for one the ability to create a new faucet should be possible through a helper function cc @siman

**Comment by F3Joule** [comment]
> tbh i think this pallet needs a change, for one the ability to create a new faucet should be possible through a helper function cc @siman

I see it like: we have a common function, but 2 different dispatch calls: `force_add_faucet`, `add_faucet`. The last one can create a faucet from caller account. The `force` one can create a faucet from any account, but caller should be root.

**Comment by Doordashcon** [comment]
@F3Joule  currently `add_faucet` dispatch can only be called by root and accepts an  accountId, `force_add_faucet` does not exist.

**Comment by F3Joule** [comment]
> @F3Joule currently `add_faucet` dispatch can only be called by root and accepts an accountId, `force_add_faucet` does not exist.

I mean, imo, we should do like I've described.

**Comment by Doordashcon** [comment]
cc @F3Joule

**Comment by Doordashcon** [comment]
@F3Joule Are the changes acceptable? I want to work on other pallets

**Comment by Doordashcon** [comment]
@F3Joule Are the changes acceptable? I want to work on other pallets

**Pull request closed without merging**
